# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
# - 0.7-beta
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - pwd
#  - julia --depwarn=no -e 'import Pkg; Pkg.clone(pwd(),"CpuId"); Pkg.build("CpuId"); Pkg.test("CpuId"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  #- julia -e 'cd(Pkg.dir("CpuId")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia --depwarn=no -e 'import Pkg; cd(Pkg.dir("CpuId")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
